$:
  vscode:
    - docker:
        build: .ide/Dockerfile
        # image: mcr.microsoft.com/devcontainers/universal
      services:
        - vscode
        - docker

feat*:
  push:
    - stages:
        - name: commitlint
          image: cnbcool/commitlint
        - name: build
          image: docker.cnb.cool/spencezhang/go-dev-demo/dockerfile-caches
          script: |
            cd gin-demo && make
        - name: build
          image: docker.cnb.cool/spencezhang/go-dev-demo/dockerfile-caches
          script: |
            cd write-gin-like-grpc && make
        - name: sync to github
          imports: https://cnb.cool/spencezhang/my-keys/-/blob/main/env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/logzh/${CNB_REPO_NAME}.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}